

use master;
IF EXISTS (SELECT name FROM sys.databases WHERE name = 'LeadsCRM')
BEGIN
    ALTER DATABASE [LeadsCRM] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [LeadsCRM];
END
GO

CREATE DATABASE [LeadsCRM];
GO

USE [LeadsCRM];
GO

CREATE TABLE [Leads] (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID()
	,FirstName NVARCHAR(25) NOT NULL
	,LastName  NVARCHAR(25) NOT NULL
	,Email     NVARCHAR(30) NOT NULL
);


