services:
  rabbitmq_messaging:
    image: rabbitmq:3-management
    container_name: rabbitmq_messaging
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Solution1Pass123!
      - RABBITMQ_ERLANG_COOKIE=unique_erlang_cookie
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_messaging_data:/var/lib/rabbitmq
      - rabbitmq_messaging_logs:/var/log/rabbitmq
    networks:
      - landing_page_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 20s

volumes:
  rabbitmq_messaging_data:
    driver: local
  rabbitmq_messaging_logs:
    driver: local

networks:
  landing_page_network:
    external: true
